print('My name is Brendan Stringer.')
print('I have a BS in Civil Engineering.')
print('I work for UVM full time managing the UVM Tech Team alongside Travis Bartlett.')
print('Our staff work at the UVM Computer Carry-In Clinic.')	
print('I practice Aikido several days a week.')
print('I have one brother, Ashten, who also attends UVM.')
print('He is studying Global Studies.')
